# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

listResolutions <- function(hicfilename, unit) {
    .Call('_trackViewer_listResolutions', PACKAGE = 'trackViewer', hicfilename, unit)
}

listUnits <- function(hicfilename) {
    .Call('_trackViewer_listUnits', PACKAGE = 'trackViewer', hicfilename)
}

listNormalizations <- function(hicfilename) {
    .Call('_trackViewer_listNormalizations', PACKAGE = 'trackViewer', hicfilename)
}

listChroms <- function(hicfilename) {
    .Call('_trackViewer_listChroms', PACKAGE = 'trackViewer', hicfilename)
}

getContactRecords <- function(hicfilename, qname1, start1, end1, qname2, start2, end2, binSize, normalization, unit) {
    .Call('_trackViewer_getContactRecords', PACKAGE = 'trackViewer', hicfilename, qname1, start1, end1, qname2, start2, end2, binSize, normalization, unit)
}

